name: "repomimic"

services:
  app_postgres:
    container_name: app-postgres
    image: pgvector/pgvector:pg16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=${APP_POSTGRES_PASSWORD}
    volumes:
      - app_postgres_data:/var/lib/postgresql/data

  app_mysql:
    container_name: app-mysql
    image: "ghcr.io/askdba/myvector:mysql8.4"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - app_mysql_data:/var/lib/mysql

  # These databases are used exclusively for the test suite.
  test_postgres:
    container_name: app-test-postgres
    image: pgvector/pgvector:pg16
    ports:
      - "${TEST_POSTGRES_PORT:-5433}:5432"
    environment:
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}

  test_mysql:
    container_name: app-test-mysql
    image: "ghcr.io/askdba/myvector:mysql8.4"
    ports:
      - "${TEST_MYSQL_PORT:-3307}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${TEST_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${TEST_MYSQL_DATABASE}

volumes:
  app_postgres_data:
  app_mysql_data: 