[project]
name = "repomimic"
version = "0.0.1"
authors = [
  { name = "Olatunji Jamaldeen Omotoyosi", email = "jamaldeen.o@yahoo.com" },
]
description = "CLI tool that indexes source code from Git repos into a database so AI can mirror their implementation patterns."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "greenlet>=3.5.6",
    "pgvector>=0.5.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
    "typer>=0.27.3",
]

[project.scripts]
repomimic = "repomimic.cli:main"

[project.urls]
"Homepage" = "https://github.com/jamaldeen09/repomimic"
"Repository" = "https://github.com/jamaldeen09/repomimic"

[project.optional-dependencies]
postgres = ["asyncpg>=0.29.0",]
sqlite = ["aiosqlite>=0.19.0",]
mysql = ["aiomysql>=0.2.0",]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

